custom:
  text_current: '{current} з {total}'
  text_previous: '« Попередня'
  text_next: 'Наступна »'
  text_close: Закрити
  slideshow:
    text_start: 'почати слайд-шоу'
    text_stop: 'зупинити слайд-шоу'
