all:
  - language_interface
  - language_content
  - language_url
configurable:
  - language_interface
  - language_url
negotiation:
  language_content:
    enabled:
      language-interface: 0
    method_weights:
      language-content-entity: -9
      language-url: -8
      language-session: -6
      language-user: -4
      language-user-anonymous: -4
      language-browser: -2
      language-interface: 9
      language-selected: 12
  language_url:
    enabled:
      language-url: 0
      language-url-fallback: 1
    method_weights:
      language-user-anonymous: -20
      language-user: -19
      language-url: -18
      language-session: -17
      language-browser: -16
      language-url-fallback: -15
      language-selected: -14
  language_interface:
    enabled:
      language-user-anonymous: -20
      language-user-admin: -19
      language-user: -18
      language-selected: -14
    method_weights:
      language-user-anonymous: -20
      language-user-admin: -19
      language-user: -18
      language-url: -17
      language-session: -16
      language-browser: -15
      language-selected: -14
_core:
  default_config_hash: dqouFqVseNJNvEjsoYKxbinFOITuCxYhi4y2OTNQP_8
