horizontal_menu: navigation
horizontal_depth: 9
off_canvas_menus: main
horizontal_wrapping_element: nav
horizontal_breakpoint: 'XL (> 1200px)'
horizontal_media_query: 'all and (min-width: 1200px)'
include_css: true
off_canvas_position: left
off_canvas_theme: theme-light
pagedim: pagedim
horizontal_superfish: true
horizontal_superfish_delay: 300
horizontal_superfish_speed: 100
horizontal_superfish_speed_out: 100
horizontal_superfish_hoverintent: true
drag: false
breakpoint_css_filepath: 'public://css'
use_breakpoint: true
allow_admin: false
wrapper_admin: true
wrapper_theme: true
use_polyfills: true
_core:
  default_config_hash: okIKWEN1iQUpeyr_635riDarUc-QmUOSwZ4nbJrYjTU
